# ===============================
# = APPLICATION
# ===============================
spring:
  application:
    name: tweetguess
  profiles:
    active: production
  thymeleaf:
    cache: true
  messages:
    basename: i18n/messages
    fallbackToSystemLocale: false
  jpa:
    show-sql: false
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    testOnBorrow: true
    validationQuery: SELECT 1
    url: jdbc:mysql://localhost:3306/tweetguessdb?useSSL=false&useUnicode=true
    username: tweetguess
    password: tweetguess
    driverClassName: com.mysql.jdbc.Driver

tweetguess:
  questionTimeLimitMilis: 20000
  questionMaxScore: 500
  questionPerGame: 10
  leaderBoardSize: 10
  choiceListSize: 4

# ===============================
# = SERVER
# ===============================
server:
  port: 8081

# ===============================
# = DEVELOPMENT
# ===============================
---
spring:
  profiles: development
  datasource:
    initialize: true
    data: classpath*:data/data.sql
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
tweetguess:
  questionPerGame: 3