# ===============================
# = APPLICATION
# ===============================
spring:
  application:
    name: tweetguess
  profiles:
    active: development
  thymeleaf:
    cache: true
  messages:
    basename: i18n/messages
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    testOnBorrow: true
    validationQuery: SELECT 1
    url: jdbc:h2:tcp://localhost:9092/mem:tweetguessdb
    username: sa
    password:
    driverClassName: org.h2.Driver

h2:
  server:
    start: true

# ===============================
# = SERVER
# ===============================
server:
  port: 8081

# ===============================
# = DEVELOPMENT
# ===============================
---
spring:
  profiles: development
  datasource:
    initialize: true
    data: classpath*:data/data.sql
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true