# ===============================
# = APPLICATION
# ===============================
spring:
  application:
    name: tweetguess-batch
  profiles:
    active: production
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    testOnBorrow: true
    validationQuery: SELECT 1
    url: jdbc:mysql://localhost:3306/tweetguessdb?useSSL=false&useUnicode=true
    username: tweetguess
    password: tweetguess
    driverClassName: com.mysql.jdbc.Driver

twitter:
  consumer-key: bYAD3vbabHH2SHKed1fgJ8aU4
  consumer-secret: SdEvFNuntCMQ0jX2JaOZFZ7zjxYcJ750Ll8PXtWNWJTK0hUjr6
  access-token: 414252605-Sf0Wr0p8U6XxucRtvduJ0wrBpAi9QvAUHHwF8wyJ
  access-token-secret: WgkJ5GR9yPXAtHrPY4ZCBo8WexQWtG3MPR7UUOoSisfqI

tweetguess:
  languageList:

# ===============================
# = DEVELOPMENT
# ===============================
---
spring:
  profiles: development
  jpa:
    show-sql: true