# ===============================
# = APPLICATION
# ===============================
spring:
  application:
    name: tweetguess-batch
  profiles:
    active: development
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    testOnBorrow: true
    validationQuery: SELECT 1
    url: jdbc:h2:tcp://localhost:9092/mem:tweetguessdb
    username: sa
    password:
    driverClassName: org.h2.Driver

twitter:
  consumer-key: bYAD3vbabHH2SHKed1fgJ8aU4
  consumer-secret: SdEvFNuntCMQ0jX2JaOZFZ7zjxYcJ750Ll8PXtWNWJTK0hUjr6
  access-token: 414252605-Sf0Wr0p8U6XxucRtvduJ0wrBpAi9QvAUHHwF8wyJ
  access-token-secret: WgkJ5GR9yPXAtHrPY4ZCBo8WexQWtG3MPR7UUOoSisfqI

tweetguess:
  choiceListSize: 4

# ===============================
# = DEVELOPMENT
# ===============================
---
spring:
  profiles: development
  jpa:
    show-sql: true