# ===============================
# = APPLICATION
# ===============================
spring:
  application:
    name: tweetguess-db
  jpa:
    show-sql: false
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    testOnBorrow: true
    validationQuery: SELECT 1
    url: jdbc:h2:tcp://localhost:9092/mem:tweetguessdb
    username: sa
    password:
    driverClassName: org.h2.Driver